# Основы программирования в Python

*Алла Тамбовцева*

## Кортежи (tuples)

Кортежи встречаются не только в программировании, но и в математике. В математике под кортежем обычно понимают упорядоченную совокупность элементов, то есть совокупность, порядок элементов которой фиксирован. В кортеже мы точно знаем, какой элемент является первым, какой – вторым, и так далее.

Внешне кортежи несильно отличаются от списков. Единственное внешнее отличие – элементы кортежа заключаются в круглые, а не в квадратные скобки.

In [1]:
t = (4, 0, 2, "abc")  

К элементам кортежа можно обращаться точно так же, как к элементам списка:

In [2]:
t[0]

4

Но, несмотря на кажущееся сходство, кортежи и списки – принципиально разные объекты. Главное отличие кортежей от списков заключается в том, что кортежи – неизменяемые объекты. Другими словами, изменять элементы кортежа нельзя. Проверим:

In [3]:
t[0] = 6

TypeError: 'tuple' object does not support item assignment

Иногда это свойство бывает полезным (некоторая «защита» от изменений), иногда – не очень, но для нас пока важно познакомиться с разными объектами в Python, чтобы потом не удивляться. Ведь многие более продвинутые функции могут возвращать результат или, наоборот, принимать на вход только кортежи или только списки.

При желании кортеж можно превратить в список:

In [4]:
list(t)

[4, 0, 2, 'abc']

И наоборот:

In [5]:
L = [5, 8, 1, -2] 

In [6]:
tuple(L)

(5, 8, 1, -2)

Если посмотреть на методы, применяемые к кортежам (например, набрать `t.` и нажать *Tab*), то можно заметить, что методов для кортежей сильно меньше по сравнению с методами для списков. 

In [7]:
t.index(4) # индекс элемента

0

In [8]:
t.count(2) # считаем 2

1

Во многом это связано с тем, что кортеж нельзя изменить. Но вот «склеивать» кортежи, создавая при этом новый, легко:

In [9]:
(1, 3) + (7, 8)

(1, 3, 7, 8)

## Массивы NumPy

Сегодня мы начнём знакомство с библиотекой NumPy (сокращение от *Numeric Python*), которая часто используется в задачах, связанных с анализом данных и машинным обучением. 

Чтобы мы смогли на конкретных примерах увидеть, зачем эта библиотека используется, давайте ее импортируем. Если вы уже устанавливали Anaconda, то библиотека NumPy также была установлена на ваш компьютер. Проверим: импортируем библиотеку с сокращённым названием, так часто делают, чтобы не «таскать» за собой в коде длинное название. Сокращение `np` для библиотеки `numpy` – общепринятое, его часто можно увидеть в документации или официальных тьюториалах.

In [10]:
import numpy as np

Основным объектом NumPy является *Ndarray* – это n-мерный массив (от *n-dimensional array*), структура данных, которая позволяет хранить набор элементов одного типа: либо целые числа, либо числа с плавающей точкой, либо строки, либо логические значения True и False. Мы пока рассмотрим одномерные массивы, которые внешне несильно отличаются от списков.

Зачем вообще нужны массивы, почему обычных списков недостаточно? Списки не позволяют выполнять операции поэлементно эффективным образом – без использования циклов и подобных конструкций. Допустим, у нас есть список чисел `L`:

In [11]:
L = [5, 8, 1 , -2] 

Если мы захотим получить новый список, состоящий из квадратов элементов списка `L`, нам придётся обращаться к циклу, применение операции ко всему списку вызовет ошибку:

In [12]:
L ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Такая особенность списков вполне логично вытекает из их структуры, которая подразумевает то, что внутри могут быть элементы разного типа. А раз так, то какой смысл позволять выполнять операции, которые имеют смысл только для одного типа данных?

С массивами такой проблемы не возникает. Если в массиве хранятся числа, мы можем свободно применить какую-нибудь операцию, работающую на числах, к каждому элементу массива. Попробуем это сделать. Создадим массив `A`:

In [13]:
A = np.array([4, 6, 7, -1, 0]) 
print(A)

[ 4  6  7 -1  0]


Возведём каждый элемент массива в квадрат:

In [14]:
A ** 2

array([16, 36, 49,  1,  0])

Получилось! Цикла не понадобилось, всё выглядит очень компактно, работает быстро!

Что удобно, похожим образом можно выполнять действия сразу с несколькими массивами одинаковой длины. Если у нас есть два списка одинаковой длины, и мы хотим посчитать попарные суммы элементов, тоже без цикла не обойтись:

In [15]:
a = [4, 6, 7, -1]
b = [5, 8, 1, 2]

# проходимся по индексам элементов от 0 до 3
# берем элементы, стоящие на одних и тех местах
# и складываем

c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[9, 14, 8, 1]


In [16]:
# или через zip()
# zip(a, b): [(4, 5), (6, 8), (7, 1), (-1, 2)]

c = []
for p in zip(a, b):
    c.append(sum(p))
print(c)

[9, 14, 8, 1]


А с массивами всё просто:

In [17]:
A = np.array(a) 
B = np.array(b) 
C = A + B
print(C)

[ 9 14  8  1]


In [18]:
A - B

array([-1, -2,  6, -3])

Или сразу несколько действий:

In [19]:
(A - B) / C * 100

array([ -11.11111111,  -14.28571429,   75.        , -300.        ])

Так как в массиве элементы должны быть одного типа, целые числа в примере выше записались в дробном виде с нулевой дробной часть (например, `75.` вместо `75`).

На этом закончим наше беглое знакомство с массивами, мы вернёмся к ним, когда будем обсуждать работу с реальными данными в табличном виде (Python будет обращаться со столбцами таблицы как с массивами с дополнительными свойствами).